[package]
name = "dynamoe-core"
version = "0.1.0"
edition = "2024"

[lib]
name = "dynamoe_core"
crate-type = ["staticlib", "cdylib", "rlib"]

[dependencies]
uniffi = { version = "0.28", features = ["build", "cli"] }

[build-dependencies]
uniffi = { version = "0.28", features = ["build"] }

[[bin]]
name = "uniffi-bindgen"
path = "src/bin/uniffi-bindgen.rs"